// Code generated by entc, DO NOT EDIT.

package tagtopic

const (
	// Label holds the string label denoting the tagtopic type in the database.
	Label = "tag_topic"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTagID holds the string denoting the tag_id field in the database.
	FieldTagID = "tag_id"
	// FieldTopicID holds the string denoting the topic_id field in the database.
	FieldTopicID = "topic_id"

	// Table holds the table name of the tagtopic in the database.
	Table = "tag_topics"
)

// Columns holds all SQL columns for tagtopic fields.
var Columns = []string{
	FieldID,
	FieldTagID,
	FieldTopicID,
}
