// Code generated by entc, DO NOT EDIT.

package userusertopic

const (
	// Label holds the string label denoting the userusertopic type in the database.
	Label = "user_user_topic"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInviterID holds the string denoting the inviter_id field in the database.
	FieldInviterID = "inviter_id"
	// FieldInvitedID holds the string denoting the invited_id field in the database.
	FieldInvitedID = "invited_id"
	// FieldTopicID holds the string denoting the topic_id field in the database.
	FieldTopicID = "topic_id"

	// Table holds the table name of the userusertopic in the database.
	Table = "user_user_topics"
)

// Columns holds all SQL columns for userusertopic fields.
var Columns = []string{
	FieldID,
	FieldInviterID,
	FieldInvitedID,
	FieldTopicID,
}
