// Code generated by entc, DO NOT EDIT.

package userusertopic

import (
	"TH0400/repo/ent/predicate"

	"github.com/facebookincubator/ent/dialect/sql"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// InviterID applies equality check predicate on the "inviter_id" field. It's identical to InviterIDEQ.
func InviterID(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldInviterID), v))
	})
}

// InvitedID applies equality check predicate on the "invited_id" field. It's identical to InvitedIDEQ.
func InvitedID(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldInvitedID), v))
	})
}

// TopicID applies equality check predicate on the "topic_id" field. It's identical to TopicIDEQ.
func TopicID(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTopicID), v))
	})
}

// InviterIDEQ applies the EQ predicate on the "inviter_id" field.
func InviterIDEQ(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldInviterID), v))
	})
}

// InviterIDNEQ applies the NEQ predicate on the "inviter_id" field.
func InviterIDNEQ(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldInviterID), v))
	})
}

// InviterIDIn applies the In predicate on the "inviter_id" field.
func InviterIDIn(vs ...int) predicate.UserUserTopic {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserUserTopic(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldInviterID), v...))
	})
}

// InviterIDNotIn applies the NotIn predicate on the "inviter_id" field.
func InviterIDNotIn(vs ...int) predicate.UserUserTopic {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserUserTopic(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldInviterID), v...))
	})
}

// InviterIDGT applies the GT predicate on the "inviter_id" field.
func InviterIDGT(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldInviterID), v))
	})
}

// InviterIDGTE applies the GTE predicate on the "inviter_id" field.
func InviterIDGTE(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldInviterID), v))
	})
}

// InviterIDLT applies the LT predicate on the "inviter_id" field.
func InviterIDLT(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldInviterID), v))
	})
}

// InviterIDLTE applies the LTE predicate on the "inviter_id" field.
func InviterIDLTE(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldInviterID), v))
	})
}

// InvitedIDEQ applies the EQ predicate on the "invited_id" field.
func InvitedIDEQ(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldInvitedID), v))
	})
}

// InvitedIDNEQ applies the NEQ predicate on the "invited_id" field.
func InvitedIDNEQ(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldInvitedID), v))
	})
}

// InvitedIDIn applies the In predicate on the "invited_id" field.
func InvitedIDIn(vs ...int) predicate.UserUserTopic {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserUserTopic(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldInvitedID), v...))
	})
}

// InvitedIDNotIn applies the NotIn predicate on the "invited_id" field.
func InvitedIDNotIn(vs ...int) predicate.UserUserTopic {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserUserTopic(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldInvitedID), v...))
	})
}

// InvitedIDGT applies the GT predicate on the "invited_id" field.
func InvitedIDGT(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldInvitedID), v))
	})
}

// InvitedIDGTE applies the GTE predicate on the "invited_id" field.
func InvitedIDGTE(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldInvitedID), v))
	})
}

// InvitedIDLT applies the LT predicate on the "invited_id" field.
func InvitedIDLT(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldInvitedID), v))
	})
}

// InvitedIDLTE applies the LTE predicate on the "invited_id" field.
func InvitedIDLTE(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldInvitedID), v))
	})
}

// TopicIDEQ applies the EQ predicate on the "topic_id" field.
func TopicIDEQ(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTopicID), v))
	})
}

// TopicIDNEQ applies the NEQ predicate on the "topic_id" field.
func TopicIDNEQ(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTopicID), v))
	})
}

// TopicIDIn applies the In predicate on the "topic_id" field.
func TopicIDIn(vs ...int) predicate.UserUserTopic {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserUserTopic(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldTopicID), v...))
	})
}

// TopicIDNotIn applies the NotIn predicate on the "topic_id" field.
func TopicIDNotIn(vs ...int) predicate.UserUserTopic {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserUserTopic(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldTopicID), v...))
	})
}

// TopicIDGT applies the GT predicate on the "topic_id" field.
func TopicIDGT(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTopicID), v))
	})
}

// TopicIDGTE applies the GTE predicate on the "topic_id" field.
func TopicIDGTE(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTopicID), v))
	})
}

// TopicIDLT applies the LT predicate on the "topic_id" field.
func TopicIDLT(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTopicID), v))
	})
}

// TopicIDLTE applies the LTE predicate on the "topic_id" field.
func TopicIDLTE(v int) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTopicID), v))
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.UserUserTopic) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.UserUserTopic) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserUserTopic) predicate.UserUserTopic {
	return predicate.UserUserTopic(func(s *sql.Selector) {
		p(s.Not())
	})
}
