// Code generated by entc, DO NOT EDIT.

package ent

import (
	"TH0400/repo/ent/predicate"
	"TH0400/repo/ent/useruser"
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// UserUserQuery is the builder for querying UserUser entities.
type UserUserQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.UserUser
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (uuq *UserUserQuery) Where(ps ...predicate.UserUser) *UserUserQuery {
	uuq.predicates = append(uuq.predicates, ps...)
	return uuq
}

// Limit adds a limit step to the query.
func (uuq *UserUserQuery) Limit(limit int) *UserUserQuery {
	uuq.limit = &limit
	return uuq
}

// Offset adds an offset step to the query.
func (uuq *UserUserQuery) Offset(offset int) *UserUserQuery {
	uuq.offset = &offset
	return uuq
}

// Order adds an order step to the query.
func (uuq *UserUserQuery) Order(o ...OrderFunc) *UserUserQuery {
	uuq.order = append(uuq.order, o...)
	return uuq
}

// First returns the first UserUser entity in the query. Returns *NotFoundError when no useruser was found.
func (uuq *UserUserQuery) First(ctx context.Context) (*UserUser, error) {
	uus, err := uuq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(uus) == 0 {
		return nil, &NotFoundError{useruser.Label}
	}
	return uus[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uuq *UserUserQuery) FirstX(ctx context.Context) *UserUser {
	uu, err := uuq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return uu
}

// FirstID returns the first UserUser id in the query. Returns *NotFoundError when no id was found.
func (uuq *UserUserQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uuq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{useruser.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (uuq *UserUserQuery) FirstXID(ctx context.Context) int {
	id, err := uuq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only UserUser entity in the query, returns an error if not exactly one entity was returned.
func (uuq *UserUserQuery) Only(ctx context.Context) (*UserUser, error) {
	uus, err := uuq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(uus) {
	case 1:
		return uus[0], nil
	case 0:
		return nil, &NotFoundError{useruser.Label}
	default:
		return nil, &NotSingularError{useruser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uuq *UserUserQuery) OnlyX(ctx context.Context) *UserUser {
	uu, err := uuq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return uu
}

// OnlyID returns the only UserUser id in the query, returns an error if not exactly one id was returned.
func (uuq *UserUserQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uuq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{useruser.Label}
	default:
		err = &NotSingularError{useruser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uuq *UserUserQuery) OnlyIDX(ctx context.Context) int {
	id, err := uuq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserUsers.
func (uuq *UserUserQuery) All(ctx context.Context) ([]*UserUser, error) {
	if err := uuq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return uuq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (uuq *UserUserQuery) AllX(ctx context.Context) []*UserUser {
	uus, err := uuq.All(ctx)
	if err != nil {
		panic(err)
	}
	return uus
}

// IDs executes the query and returns a list of UserUser ids.
func (uuq *UserUserQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := uuq.Select(useruser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uuq *UserUserQuery) IDsX(ctx context.Context) []int {
	ids, err := uuq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uuq *UserUserQuery) Count(ctx context.Context) (int, error) {
	if err := uuq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return uuq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (uuq *UserUserQuery) CountX(ctx context.Context) int {
	count, err := uuq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uuq *UserUserQuery) Exist(ctx context.Context) (bool, error) {
	if err := uuq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return uuq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (uuq *UserUserQuery) ExistX(ctx context.Context) bool {
	exist, err := uuq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uuq *UserUserQuery) Clone() *UserUserQuery {
	return &UserUserQuery{
		config:     uuq.config,
		limit:      uuq.limit,
		offset:     uuq.offset,
		order:      append([]OrderFunc{}, uuq.order...),
		unique:     append([]string{}, uuq.unique...),
		predicates: append([]predicate.UserUser{}, uuq.predicates...),
		// clone intermediate query.
		sql:  uuq.sql.Clone(),
		path: uuq.path,
	}
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		IdolID int `json:"idol_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserUser.Query().
//		GroupBy(useruser.FieldIdolID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (uuq *UserUserQuery) GroupBy(field string, fields ...string) *UserUserGroupBy {
	group := &UserUserGroupBy{config: uuq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := uuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return uuq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		IdolID int `json:"idol_id,omitempty"`
//	}
//
//	client.UserUser.Query().
//		Select(useruser.FieldIdolID).
//		Scan(ctx, &v)
//
func (uuq *UserUserQuery) Select(field string, fields ...string) *UserUserSelect {
	selector := &UserUserSelect{config: uuq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := uuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return uuq.sqlQuery(), nil
	}
	return selector
}

func (uuq *UserUserQuery) prepareQuery(ctx context.Context) error {
	if uuq.path != nil {
		prev, err := uuq.path(ctx)
		if err != nil {
			return err
		}
		uuq.sql = prev
	}
	return nil
}

func (uuq *UserUserQuery) sqlAll(ctx context.Context) ([]*UserUser, error) {
	var (
		nodes = []*UserUser{}
		_spec = uuq.querySpec()
	)
	_spec.ScanValues = func() []interface{} {
		node := &UserUser{config: uuq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, uuq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (uuq *UserUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uuq.querySpec()
	return sqlgraph.CountNodes(ctx, uuq.driver, _spec)
}

func (uuq *UserUserQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := uuq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (uuq *UserUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   useruser.Table,
			Columns: useruser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: useruser.FieldID,
			},
		},
		From:   uuq.sql,
		Unique: true,
	}
	if ps := uuq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uuq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uuq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uuq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uuq *UserUserQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(uuq.driver.Dialect())
	t1 := builder.Table(useruser.Table)
	selector := builder.Select(t1.Columns(useruser.Columns...)...).From(t1)
	if uuq.sql != nil {
		selector = uuq.sql
		selector.Select(selector.Columns(useruser.Columns...)...)
	}
	for _, p := range uuq.predicates {
		p(selector)
	}
	for _, p := range uuq.order {
		p(selector)
	}
	if offset := uuq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uuq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserUserGroupBy is the builder for group-by UserUser entities.
type UserUserGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uugb *UserUserGroupBy) Aggregate(fns ...AggregateFunc) *UserUserGroupBy {
	uugb.fns = append(uugb.fns, fns...)
	return uugb
}

// Scan applies the group-by query and scan the result into the given value.
func (uugb *UserUserGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := uugb.path(ctx)
	if err != nil {
		return err
	}
	uugb.sql = query
	return uugb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (uugb *UserUserGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := uugb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (uugb *UserUserGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(uugb.fields) > 1 {
		return nil, errors.New("ent: UserUserGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := uugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (uugb *UserUserGroupBy) StringsX(ctx context.Context) []string {
	v, err := uugb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (uugb *UserUserGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = uugb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useruser.Label}
	default:
		err = fmt.Errorf("ent: UserUserGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (uugb *UserUserGroupBy) StringX(ctx context.Context) string {
	v, err := uugb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (uugb *UserUserGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(uugb.fields) > 1 {
		return nil, errors.New("ent: UserUserGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := uugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (uugb *UserUserGroupBy) IntsX(ctx context.Context) []int {
	v, err := uugb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (uugb *UserUserGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = uugb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useruser.Label}
	default:
		err = fmt.Errorf("ent: UserUserGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (uugb *UserUserGroupBy) IntX(ctx context.Context) int {
	v, err := uugb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (uugb *UserUserGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(uugb.fields) > 1 {
		return nil, errors.New("ent: UserUserGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := uugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (uugb *UserUserGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := uugb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (uugb *UserUserGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = uugb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useruser.Label}
	default:
		err = fmt.Errorf("ent: UserUserGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (uugb *UserUserGroupBy) Float64X(ctx context.Context) float64 {
	v, err := uugb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (uugb *UserUserGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(uugb.fields) > 1 {
		return nil, errors.New("ent: UserUserGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := uugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (uugb *UserUserGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := uugb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (uugb *UserUserGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = uugb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useruser.Label}
	default:
		err = fmt.Errorf("ent: UserUserGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (uugb *UserUserGroupBy) BoolX(ctx context.Context) bool {
	v, err := uugb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uugb *UserUserGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := uugb.sqlQuery().Query()
	if err := uugb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (uugb *UserUserGroupBy) sqlQuery() *sql.Selector {
	selector := uugb.sql
	columns := make([]string, 0, len(uugb.fields)+len(uugb.fns))
	columns = append(columns, uugb.fields...)
	for _, fn := range uugb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(uugb.fields...)
}

// UserUserSelect is the builder for select fields of UserUser entities.
type UserUserSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (uus *UserUserSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := uus.path(ctx)
	if err != nil {
		return err
	}
	uus.sql = query
	return uus.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (uus *UserUserSelect) ScanX(ctx context.Context, v interface{}) {
	if err := uus.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (uus *UserUserSelect) Strings(ctx context.Context) ([]string, error) {
	if len(uus.fields) > 1 {
		return nil, errors.New("ent: UserUserSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := uus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (uus *UserUserSelect) StringsX(ctx context.Context) []string {
	v, err := uus.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (uus *UserUserSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = uus.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useruser.Label}
	default:
		err = fmt.Errorf("ent: UserUserSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (uus *UserUserSelect) StringX(ctx context.Context) string {
	v, err := uus.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (uus *UserUserSelect) Ints(ctx context.Context) ([]int, error) {
	if len(uus.fields) > 1 {
		return nil, errors.New("ent: UserUserSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := uus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (uus *UserUserSelect) IntsX(ctx context.Context) []int {
	v, err := uus.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (uus *UserUserSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = uus.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useruser.Label}
	default:
		err = fmt.Errorf("ent: UserUserSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (uus *UserUserSelect) IntX(ctx context.Context) int {
	v, err := uus.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (uus *UserUserSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(uus.fields) > 1 {
		return nil, errors.New("ent: UserUserSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := uus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (uus *UserUserSelect) Float64sX(ctx context.Context) []float64 {
	v, err := uus.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (uus *UserUserSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = uus.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useruser.Label}
	default:
		err = fmt.Errorf("ent: UserUserSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (uus *UserUserSelect) Float64X(ctx context.Context) float64 {
	v, err := uus.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (uus *UserUserSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(uus.fields) > 1 {
		return nil, errors.New("ent: UserUserSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := uus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (uus *UserUserSelect) BoolsX(ctx context.Context) []bool {
	v, err := uus.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (uus *UserUserSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = uus.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{useruser.Label}
	default:
		err = fmt.Errorf("ent: UserUserSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (uus *UserUserSelect) BoolX(ctx context.Context) bool {
	v, err := uus.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uus *UserUserSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := uus.sqlQuery().Query()
	if err := uus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (uus *UserUserSelect) sqlQuery() sql.Querier {
	selector := uus.sql
	selector.Select(selector.Columns(uus.fields...)...)
	return selector
}
