// Code generated by entc, DO NOT EDIT.

package ent

import (
	"TH0400/repo/ent/predicate"
	"TH0400/repo/ent/usertopic"
	"context"
	"errors"
	"fmt"
	"math"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// UserTopicQuery is the builder for querying UserTopic entities.
type UserTopicQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.UserTopic
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (utq *UserTopicQuery) Where(ps ...predicate.UserTopic) *UserTopicQuery {
	utq.predicates = append(utq.predicates, ps...)
	return utq
}

// Limit adds a limit step to the query.
func (utq *UserTopicQuery) Limit(limit int) *UserTopicQuery {
	utq.limit = &limit
	return utq
}

// Offset adds an offset step to the query.
func (utq *UserTopicQuery) Offset(offset int) *UserTopicQuery {
	utq.offset = &offset
	return utq
}

// Order adds an order step to the query.
func (utq *UserTopicQuery) Order(o ...OrderFunc) *UserTopicQuery {
	utq.order = append(utq.order, o...)
	return utq
}

// First returns the first UserTopic entity in the query. Returns *NotFoundError when no usertopic was found.
func (utq *UserTopicQuery) First(ctx context.Context) (*UserTopic, error) {
	uts, err := utq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(uts) == 0 {
		return nil, &NotFoundError{usertopic.Label}
	}
	return uts[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (utq *UserTopicQuery) FirstX(ctx context.Context) *UserTopic {
	ut, err := utq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return ut
}

// FirstID returns the first UserTopic id in the query. Returns *NotFoundError when no id was found.
func (utq *UserTopicQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = utq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usertopic.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (utq *UserTopicQuery) FirstXID(ctx context.Context) int {
	id, err := utq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only UserTopic entity in the query, returns an error if not exactly one entity was returned.
func (utq *UserTopicQuery) Only(ctx context.Context) (*UserTopic, error) {
	uts, err := utq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(uts) {
	case 1:
		return uts[0], nil
	case 0:
		return nil, &NotFoundError{usertopic.Label}
	default:
		return nil, &NotSingularError{usertopic.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (utq *UserTopicQuery) OnlyX(ctx context.Context) *UserTopic {
	ut, err := utq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return ut
}

// OnlyID returns the only UserTopic id in the query, returns an error if not exactly one id was returned.
func (utq *UserTopicQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = utq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usertopic.Label}
	default:
		err = &NotSingularError{usertopic.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (utq *UserTopicQuery) OnlyIDX(ctx context.Context) int {
	id, err := utq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserTopics.
func (utq *UserTopicQuery) All(ctx context.Context) ([]*UserTopic, error) {
	if err := utq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return utq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (utq *UserTopicQuery) AllX(ctx context.Context) []*UserTopic {
	uts, err := utq.All(ctx)
	if err != nil {
		panic(err)
	}
	return uts
}

// IDs executes the query and returns a list of UserTopic ids.
func (utq *UserTopicQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := utq.Select(usertopic.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (utq *UserTopicQuery) IDsX(ctx context.Context) []int {
	ids, err := utq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (utq *UserTopicQuery) Count(ctx context.Context) (int, error) {
	if err := utq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return utq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (utq *UserTopicQuery) CountX(ctx context.Context) int {
	count, err := utq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (utq *UserTopicQuery) Exist(ctx context.Context) (bool, error) {
	if err := utq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return utq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (utq *UserTopicQuery) ExistX(ctx context.Context) bool {
	exist, err := utq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (utq *UserTopicQuery) Clone() *UserTopicQuery {
	return &UserTopicQuery{
		config:     utq.config,
		limit:      utq.limit,
		offset:     utq.offset,
		order:      append([]OrderFunc{}, utq.order...),
		unique:     append([]string{}, utq.unique...),
		predicates: append([]predicate.UserTopic{}, utq.predicates...),
		// clone intermediate query.
		sql:  utq.sql.Clone(),
		path: utq.path,
	}
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserTopic.Query().
//		GroupBy(usertopic.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (utq *UserTopicQuery) GroupBy(field string, fields ...string) *UserTopicGroupBy {
	group := &UserTopicGroupBy{config: utq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := utq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return utq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//	}
//
//	client.UserTopic.Query().
//		Select(usertopic.FieldUserID).
//		Scan(ctx, &v)
//
func (utq *UserTopicQuery) Select(field string, fields ...string) *UserTopicSelect {
	selector := &UserTopicSelect{config: utq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := utq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return utq.sqlQuery(), nil
	}
	return selector
}

func (utq *UserTopicQuery) prepareQuery(ctx context.Context) error {
	if utq.path != nil {
		prev, err := utq.path(ctx)
		if err != nil {
			return err
		}
		utq.sql = prev
	}
	return nil
}

func (utq *UserTopicQuery) sqlAll(ctx context.Context) ([]*UserTopic, error) {
	var (
		nodes = []*UserTopic{}
		_spec = utq.querySpec()
	)
	_spec.ScanValues = func() []interface{} {
		node := &UserTopic{config: utq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, utq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (utq *UserTopicQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := utq.querySpec()
	return sqlgraph.CountNodes(ctx, utq.driver, _spec)
}

func (utq *UserTopicQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := utq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (utq *UserTopicQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   usertopic.Table,
			Columns: usertopic.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usertopic.FieldID,
			},
		},
		From:   utq.sql,
		Unique: true,
	}
	if ps := utq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := utq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := utq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := utq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (utq *UserTopicQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(utq.driver.Dialect())
	t1 := builder.Table(usertopic.Table)
	selector := builder.Select(t1.Columns(usertopic.Columns...)...).From(t1)
	if utq.sql != nil {
		selector = utq.sql
		selector.Select(selector.Columns(usertopic.Columns...)...)
	}
	for _, p := range utq.predicates {
		p(selector)
	}
	for _, p := range utq.order {
		p(selector)
	}
	if offset := utq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := utq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserTopicGroupBy is the builder for group-by UserTopic entities.
type UserTopicGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (utgb *UserTopicGroupBy) Aggregate(fns ...AggregateFunc) *UserTopicGroupBy {
	utgb.fns = append(utgb.fns, fns...)
	return utgb
}

// Scan applies the group-by query and scan the result into the given value.
func (utgb *UserTopicGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := utgb.path(ctx)
	if err != nil {
		return err
	}
	utgb.sql = query
	return utgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (utgb *UserTopicGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := utgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (utgb *UserTopicGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(utgb.fields) > 1 {
		return nil, errors.New("ent: UserTopicGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := utgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (utgb *UserTopicGroupBy) StringsX(ctx context.Context) []string {
	v, err := utgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (utgb *UserTopicGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = utgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usertopic.Label}
	default:
		err = fmt.Errorf("ent: UserTopicGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (utgb *UserTopicGroupBy) StringX(ctx context.Context) string {
	v, err := utgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (utgb *UserTopicGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(utgb.fields) > 1 {
		return nil, errors.New("ent: UserTopicGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := utgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (utgb *UserTopicGroupBy) IntsX(ctx context.Context) []int {
	v, err := utgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (utgb *UserTopicGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = utgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usertopic.Label}
	default:
		err = fmt.Errorf("ent: UserTopicGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (utgb *UserTopicGroupBy) IntX(ctx context.Context) int {
	v, err := utgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (utgb *UserTopicGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(utgb.fields) > 1 {
		return nil, errors.New("ent: UserTopicGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := utgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (utgb *UserTopicGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := utgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (utgb *UserTopicGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = utgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usertopic.Label}
	default:
		err = fmt.Errorf("ent: UserTopicGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (utgb *UserTopicGroupBy) Float64X(ctx context.Context) float64 {
	v, err := utgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (utgb *UserTopicGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(utgb.fields) > 1 {
		return nil, errors.New("ent: UserTopicGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := utgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (utgb *UserTopicGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := utgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (utgb *UserTopicGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = utgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usertopic.Label}
	default:
		err = fmt.Errorf("ent: UserTopicGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (utgb *UserTopicGroupBy) BoolX(ctx context.Context) bool {
	v, err := utgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (utgb *UserTopicGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := utgb.sqlQuery().Query()
	if err := utgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (utgb *UserTopicGroupBy) sqlQuery() *sql.Selector {
	selector := utgb.sql
	columns := make([]string, 0, len(utgb.fields)+len(utgb.fns))
	columns = append(columns, utgb.fields...)
	for _, fn := range utgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(utgb.fields...)
}

// UserTopicSelect is the builder for select fields of UserTopic entities.
type UserTopicSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (uts *UserTopicSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := uts.path(ctx)
	if err != nil {
		return err
	}
	uts.sql = query
	return uts.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (uts *UserTopicSelect) ScanX(ctx context.Context, v interface{}) {
	if err := uts.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (uts *UserTopicSelect) Strings(ctx context.Context) ([]string, error) {
	if len(uts.fields) > 1 {
		return nil, errors.New("ent: UserTopicSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := uts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (uts *UserTopicSelect) StringsX(ctx context.Context) []string {
	v, err := uts.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (uts *UserTopicSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = uts.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usertopic.Label}
	default:
		err = fmt.Errorf("ent: UserTopicSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (uts *UserTopicSelect) StringX(ctx context.Context) string {
	v, err := uts.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (uts *UserTopicSelect) Ints(ctx context.Context) ([]int, error) {
	if len(uts.fields) > 1 {
		return nil, errors.New("ent: UserTopicSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := uts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (uts *UserTopicSelect) IntsX(ctx context.Context) []int {
	v, err := uts.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (uts *UserTopicSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = uts.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usertopic.Label}
	default:
		err = fmt.Errorf("ent: UserTopicSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (uts *UserTopicSelect) IntX(ctx context.Context) int {
	v, err := uts.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (uts *UserTopicSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(uts.fields) > 1 {
		return nil, errors.New("ent: UserTopicSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := uts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (uts *UserTopicSelect) Float64sX(ctx context.Context) []float64 {
	v, err := uts.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (uts *UserTopicSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = uts.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usertopic.Label}
	default:
		err = fmt.Errorf("ent: UserTopicSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (uts *UserTopicSelect) Float64X(ctx context.Context) float64 {
	v, err := uts.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (uts *UserTopicSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(uts.fields) > 1 {
		return nil, errors.New("ent: UserTopicSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := uts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (uts *UserTopicSelect) BoolsX(ctx context.Context) []bool {
	v, err := uts.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (uts *UserTopicSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = uts.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usertopic.Label}
	default:
		err = fmt.Errorf("ent: UserTopicSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (uts *UserTopicSelect) BoolX(ctx context.Context) bool {
	v, err := uts.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uts *UserTopicSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := uts.sqlQuery().Query()
	if err := uts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (uts *UserTopicSelect) sqlQuery() sql.Querier {
	selector := uts.sql
	selector.Select(selector.Columns(uts.fields...)...)
	return selector
}
