// Code generated by entc, DO NOT EDIT.

package ent

import (
	"TH0400/repo/ent/predicate"
	"TH0400/repo/ent/useruser"
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// UserUserUpdate is the builder for updating UserUser entities.
type UserUserUpdate struct {
	config
	hooks      []Hook
	mutation   *UserUserMutation
	predicates []predicate.UserUser
}

// Where adds a new predicate for the builder.
func (uuu *UserUserUpdate) Where(ps ...predicate.UserUser) *UserUserUpdate {
	uuu.predicates = append(uuu.predicates, ps...)
	return uuu
}

// Mutation returns the UserUserMutation object of the builder.
func (uuu *UserUserUpdate) Mutation() *UserUserMutation {
	return uuu.mutation
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (uuu *UserUserUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(uuu.hooks) == 0 {
		affected, err = uuu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uuu.mutation = mutation
			affected, err = uuu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uuu.hooks) - 1; i >= 0; i-- {
			mut = uuu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uuu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (uuu *UserUserUpdate) SaveX(ctx context.Context) int {
	affected, err := uuu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uuu *UserUserUpdate) Exec(ctx context.Context) error {
	_, err := uuu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuu *UserUserUpdate) ExecX(ctx context.Context) {
	if err := uuu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uuu *UserUserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   useruser.Table,
			Columns: useruser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: useruser.FieldID,
			},
		},
	}
	if ps := uuu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uuu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useruser.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// UserUserUpdateOne is the builder for updating a single UserUser entity.
type UserUserUpdateOne struct {
	config
	hooks    []Hook
	mutation *UserUserMutation
}

// Mutation returns the UserUserMutation object of the builder.
func (uuuo *UserUserUpdateOne) Mutation() *UserUserMutation {
	return uuuo.mutation
}

// Save executes the query and returns the updated entity.
func (uuuo *UserUserUpdateOne) Save(ctx context.Context) (*UserUser, error) {
	var (
		err  error
		node *UserUser
	)
	if len(uuuo.hooks) == 0 {
		node, err = uuuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uuuo.mutation = mutation
			node, err = uuuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(uuuo.hooks) - 1; i >= 0; i-- {
			mut = uuuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uuuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (uuuo *UserUserUpdateOne) SaveX(ctx context.Context) *UserUser {
	uu, err := uuuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return uu
}

// Exec executes the query on the entity.
func (uuuo *UserUserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuuo *UserUserUpdateOne) ExecX(ctx context.Context) {
	if err := uuuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uuuo *UserUserUpdateOne) sqlSave(ctx context.Context) (uu *UserUser, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   useruser.Table,
			Columns: useruser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: useruser.FieldID,
			},
		},
	}
	id, ok := uuuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing UserUser.ID for update")}
	}
	_spec.Node.ID.Value = id
	uu = &UserUser{config: uuuo.config}
	_spec.Assign = uu.assignValues
	_spec.ScanValues = uu.scanValues()
	if err = sqlgraph.UpdateNode(ctx, uuuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useruser.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return uu, nil
}
