// Code generated by entc, DO NOT EDIT.

package ent

import (
	"TH0400/repo/ent/userusertopic"
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
)

// UserUserTopic is the model entity for the UserUserTopic schema.
type UserUserTopic struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// InviterID holds the value of the "inviter_id" field.
	InviterID int `json:"inviter_id,omitempty"`
	// InvitedID holds the value of the "invited_id" field.
	InvitedID int `json:"invited_id,omitempty"`
	// TopicID holds the value of the "topic_id" field.
	TopicID int `json:"topic_id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserUserTopic) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // id
		&sql.NullInt64{}, // inviter_id
		&sql.NullInt64{}, // invited_id
		&sql.NullInt64{}, // topic_id
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserUserTopic fields.
func (uut *UserUserTopic) assignValues(values ...interface{}) error {
	if m, n := len(values), len(userusertopic.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	uut.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field inviter_id", values[0])
	} else if value.Valid {
		uut.InviterID = int(value.Int64)
	}
	if value, ok := values[1].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field invited_id", values[1])
	} else if value.Valid {
		uut.InvitedID = int(value.Int64)
	}
	if value, ok := values[2].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field topic_id", values[2])
	} else if value.Valid {
		uut.TopicID = int(value.Int64)
	}
	return nil
}

// Update returns a builder for updating this UserUserTopic.
// Note that, you need to call UserUserTopic.Unwrap() before calling this method, if this UserUserTopic
// was returned from a transaction, and the transaction was committed or rolled back.
func (uut *UserUserTopic) Update() *UserUserTopicUpdateOne {
	return (&UserUserTopicClient{config: uut.config}).UpdateOne(uut)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (uut *UserUserTopic) Unwrap() *UserUserTopic {
	tx, ok := uut.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserUserTopic is not a transactional entity")
	}
	uut.config.driver = tx.drv
	return uut
}

// String implements the fmt.Stringer.
func (uut *UserUserTopic) String() string {
	var builder strings.Builder
	builder.WriteString("UserUserTopic(")
	builder.WriteString(fmt.Sprintf("id=%v", uut.ID))
	builder.WriteString(", inviter_id=")
	builder.WriteString(fmt.Sprintf("%v", uut.InviterID))
	builder.WriteString(", invited_id=")
	builder.WriteString(fmt.Sprintf("%v", uut.InvitedID))
	builder.WriteString(", topic_id=")
	builder.WriteString(fmt.Sprintf("%v", uut.TopicID))
	builder.WriteByte(')')
	return builder.String()
}

// UserUserTopics is a parsable slice of UserUserTopic.
type UserUserTopics []*UserUserTopic

func (uut UserUserTopics) config(cfg config) {
	for _i := range uut {
		uut[_i].config = cfg
	}
}
