// Code generated by entc, DO NOT EDIT.

package ent

import (
	"TH0400/repo/ent/predicate"
	"TH0400/repo/ent/userusertopic"
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// UserUserTopicUpdate is the builder for updating UserUserTopic entities.
type UserUserTopicUpdate struct {
	config
	hooks      []Hook
	mutation   *UserUserTopicMutation
	predicates []predicate.UserUserTopic
}

// Where adds a new predicate for the builder.
func (uutu *UserUserTopicUpdate) Where(ps ...predicate.UserUserTopic) *UserUserTopicUpdate {
	uutu.predicates = append(uutu.predicates, ps...)
	return uutu
}

// Mutation returns the UserUserTopicMutation object of the builder.
func (uutu *UserUserTopicUpdate) Mutation() *UserUserTopicMutation {
	return uutu.mutation
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (uutu *UserUserTopicUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(uutu.hooks) == 0 {
		affected, err = uutu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserUserTopicMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uutu.mutation = mutation
			affected, err = uutu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uutu.hooks) - 1; i >= 0; i-- {
			mut = uutu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uutu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (uutu *UserUserTopicUpdate) SaveX(ctx context.Context) int {
	affected, err := uutu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uutu *UserUserTopicUpdate) Exec(ctx context.Context) error {
	_, err := uutu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uutu *UserUserTopicUpdate) ExecX(ctx context.Context) {
	if err := uutu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uutu *UserUserTopicUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userusertopic.Table,
			Columns: userusertopic.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userusertopic.FieldID,
			},
		},
	}
	if ps := uutu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uutu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userusertopic.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// UserUserTopicUpdateOne is the builder for updating a single UserUserTopic entity.
type UserUserTopicUpdateOne struct {
	config
	hooks    []Hook
	mutation *UserUserTopicMutation
}

// Mutation returns the UserUserTopicMutation object of the builder.
func (uutuo *UserUserTopicUpdateOne) Mutation() *UserUserTopicMutation {
	return uutuo.mutation
}

// Save executes the query and returns the updated entity.
func (uutuo *UserUserTopicUpdateOne) Save(ctx context.Context) (*UserUserTopic, error) {
	var (
		err  error
		node *UserUserTopic
	)
	if len(uutuo.hooks) == 0 {
		node, err = uutuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserUserTopicMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uutuo.mutation = mutation
			node, err = uutuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(uutuo.hooks) - 1; i >= 0; i-- {
			mut = uutuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uutuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (uutuo *UserUserTopicUpdateOne) SaveX(ctx context.Context) *UserUserTopic {
	uut, err := uutuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return uut
}

// Exec executes the query on the entity.
func (uutuo *UserUserTopicUpdateOne) Exec(ctx context.Context) error {
	_, err := uutuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uutuo *UserUserTopicUpdateOne) ExecX(ctx context.Context) {
	if err := uutuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uutuo *UserUserTopicUpdateOne) sqlSave(ctx context.Context) (uut *UserUserTopic, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userusertopic.Table,
			Columns: userusertopic.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userusertopic.FieldID,
			},
		},
	}
	id, ok := uutuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing UserUserTopic.ID for update")}
	}
	_spec.Node.ID.Value = id
	uut = &UserUserTopic{config: uutuo.config}
	_spec.Assign = uut.assignValues
	_spec.ScanValues = uut.scanValues()
	if err = sqlgraph.UpdateNode(ctx, uutuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userusertopic.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return uut, nil
}
