// Code generated by entc, DO NOT EDIT.

package ent

import (
	"TH0400/repo/ent/predicate"
	"TH0400/repo/ent/useruser"
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// UserUserDelete is the builder for deleting a UserUser entity.
type UserUserDelete struct {
	config
	hooks      []Hook
	mutation   *UserUserMutation
	predicates []predicate.UserUser
}

// Where adds a new predicate to the delete builder.
func (uud *UserUserDelete) Where(ps ...predicate.UserUser) *UserUserDelete {
	uud.predicates = append(uud.predicates, ps...)
	return uud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uud *UserUserDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(uud.hooks) == 0 {
		affected, err = uud.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uud.mutation = mutation
			affected, err = uud.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uud.hooks) - 1; i >= 0; i-- {
			mut = uud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (uud *UserUserDelete) ExecX(ctx context.Context) int {
	n, err := uud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uud *UserUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: useruser.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: useruser.FieldID,
			},
		},
	}
	if ps := uud.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, uud.driver, _spec)
}

// UserUserDeleteOne is the builder for deleting a single UserUser entity.
type UserUserDeleteOne struct {
	uud *UserUserDelete
}

// Exec executes the deletion query.
func (uudo *UserUserDeleteOne) Exec(ctx context.Context) error {
	n, err := uudo.uud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{useruser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uudo *UserUserDeleteOne) ExecX(ctx context.Context) {
	uudo.uud.ExecX(ctx)
}
