// Code generated by entc, DO NOT EDIT.

package ent

import (
	"TH0400/repo/ent/predicate"
	"TH0400/repo/ent/usertopic"
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// UserTopicDelete is the builder for deleting a UserTopic entity.
type UserTopicDelete struct {
	config
	hooks      []Hook
	mutation   *UserTopicMutation
	predicates []predicate.UserTopic
}

// Where adds a new predicate to the delete builder.
func (utd *UserTopicDelete) Where(ps ...predicate.UserTopic) *UserTopicDelete {
	utd.predicates = append(utd.predicates, ps...)
	return utd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (utd *UserTopicDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(utd.hooks) == 0 {
		affected, err = utd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserTopicMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			utd.mutation = mutation
			affected, err = utd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(utd.hooks) - 1; i >= 0; i-- {
			mut = utd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, utd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (utd *UserTopicDelete) ExecX(ctx context.Context) int {
	n, err := utd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (utd *UserTopicDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: usertopic.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: usertopic.FieldID,
			},
		},
	}
	if ps := utd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, utd.driver, _spec)
}

// UserTopicDeleteOne is the builder for deleting a single UserTopic entity.
type UserTopicDeleteOne struct {
	utd *UserTopicDelete
}

// Exec executes the deletion query.
func (utdo *UserTopicDeleteOne) Exec(ctx context.Context) error {
	n, err := utdo.utd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usertopic.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (utdo *UserTopicDeleteOne) ExecX(ctx context.Context) {
	utdo.utd.ExecX(ctx)
}
