// Code generated by entc, DO NOT EDIT.

package usertopic

const (
	// Label holds the string label denoting the usertopic type in the database.
	Label = "user_topic"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldTopicID holds the string denoting the topic_id field in the database.
	FieldTopicID = "topic_id"

	// Table holds the table name of the usertopic in the database.
	Table = "user_topics"
)

// Columns holds all SQL columns for usertopic fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldTopicID,
}
