// Code generated by entc, DO NOT EDIT.

package useruser

const (
	// Label holds the string label denoting the useruser type in the database.
	Label = "user_user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIdolID holds the string denoting the idol_id field in the database.
	FieldIdolID = "idol_id"
	// FieldFollowerID holds the string denoting the follower_id field in the database.
	FieldFollowerID = "follower_id"

	// Table holds the table name of the useruser in the database.
	Table = "user_users"
)

// Columns holds all SQL columns for useruser fields.
var Columns = []string{
	FieldID,
	FieldIdolID,
	FieldFollowerID,
}
