// Code generated by entc, DO NOT EDIT.

package topic

import (
	"time"
)

const (
	// Label holds the string label denoting the topic type in the database.
	Label = "topic"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldIsReleased holds the string denoting the is_released field in the database.
	FieldIsReleased = "is_released"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCreaterID holds the string denoting the creater_id field in the database.
	FieldCreaterID = "creater_id"

	// Table holds the table name of the topic in the database.
	Table = "topics"
)

// Columns holds all SQL columns for topic fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldContent,
	FieldIsReleased,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCreaterID,
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultContent holds the default value on creation for the content field.
	DefaultContent string
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt func() time.Time
)
