// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Answer is the predicate function for answer builders.
type Answer func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// TagTopic is the predicate function for tagtopic builders.
type TagTopic func(*sql.Selector)

// Topic is the predicate function for topic builders.
type Topic func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserTopic is the predicate function for usertopic builders.
type UserTopic func(*sql.Selector)

// UserUser is the predicate function for useruser builders.
type UserUser func(*sql.Selector)

// UserUserTopic is the predicate function for userusertopic builders.
type UserUserTopic func(*sql.Selector)
